services:
  - type: web
    name: flask-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: PORT
        value: 10000
